set(_CATKIN_CURRENT_PACKAGE "dockeros")
set(dockeros_VERSION "1.0.0")
set(dockeros_MAINTAINER "ct2034 <christian.henkel@ipa.fraunhofer.de>")
set(dockeros_PACKAGE_FORMAT "1")
set(dockeros_BUILD_DEPENDS "rospy")
set(dockeros_BUILD_EXPORT_DEPENDS "rospy")
set(dockeros_BUILDTOOL_DEPENDS "catkin")
set(dockeros_BUILDTOOL_EXPORT_DEPENDS )
set(dockeros_EXEC_DEPENDS "rospy")
set(dockeros_RUN_DEPENDS "rospy")
set(dockeros_TEST_DEPENDS )
set(dockeros_DOC_DEPENDS )
set(dockeros_URL_WEBSITE "")
set(dockeros_URL_BUGTRACKER "")
set(dockeros_URL_REPOSITORY "")
set(dockeros_DEPRECATED "")